export { default as HomeBanner } from "./HomeBanner";
export { default as HomeClientSays } from "./HomeClientSays";
export { default as HomeHowCanHelp } from "./HomeHowCanHelp";
export { default as HomeLatestTechnology } from "./HomeLatestTechnology";
export { default as HomeOurExpertise } from "./HomeOurExpertise";
export { default as HomeLatestThinking } from "./HomeLatestThinking";
export { default as HomeClients } from "./HomeClients";
export { default as HomeHowWeCollaborate } from "./HomeHowWeCollaborate";
export { default as HomeSwiper } from "./HomeSwiper";
